### ISSUE TITLE
Missing GradInversion Additional Information other than Gradient

### ISSUE THREAD

**Issue by philipjk** [Princeton-SysML/GradAttack#3]
In the documentation relative to the papers introducing gradient inversion attacks (`GradAttack/papers/gradient_inversion.md`) the GradInversion paper by Yin et al. lists "Good approximation of private labels" as additional information needed other than gradient. 

The table entry is missing that the above paper also requires BatchNorm statistics (Section 3.3) as part of the regularization terms.

**Comment by Hazelsuko07** [comment]
Hi,

Thanks for your suggestion! We've updated the requirements of GradInversion by including BatchNorm statistics :)
